# 项目相关配置
gsh:
  # 名称
  name: GSH
  # 版本
  version: 4.0.0
  # 版权年份
  copyrightYear: 2019
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/gsh/uploadPath，Linux配置 /home/gsh/uploadPath）
  profile: /gsh/uploadPath
  # 获取ip地址开关
  addressEnabled: true
  # 接入平台默认根组织结构父节点
  factoryDeptRootId: 100
  # 接入平台默认角色组
  factoryDefaultRoleIds: 2
  # 平台缓存模式 ehcache，redis（redis需要配置spring的redis参数）
  framworkCacheMode: redis
  # 文件存储方式: : minio、disk，（minio需要minio存储配置）
  fileStorageMode: disk
  # 在线session存储位置db redis默认是redis
  onlineSessionStore: db
  # session存储位置redis的数据库编号
  redisSessionDatabase: 0
  #产品vip管理地址
  prodRestUrl: http://localhost:8092/prod
  #开启租户系统  开启:true,关闭:false
  factoryDisplayMode: true
  #开启产品系统（向产品系统同步数据）
  syncDataToProd: false
  #与产品系统统一数据库
  prodDBUnified: false
  #租户默认学员数
  prodDefaultAccountNum: 30
  #租户默认在线人数
  prodDefaultOnlineUserNum: 30
  #租户默认vip级别
  prodDefaultVersion: vip0
  #租户默认vip级别名称
  prodDefaultVersionName: 普通版
  #租户vip权限天数
  prodDefaultVipDays: 1000
  #支付到付款的最大时间 m:分钟 h:小时 d:天 c:当天
  payTimeoutExpress: 90m
  #生成的支付二维码地址（不带参数）
  payQRcodeUrl: http://localhost:8099/gsh/order/QRcode/pay
  #支付后异步回调地址
  payNotifyUrl: http://localhost:8099/gsh/order/notify
  #支付后同步回显地址
  payReturnUrl: http://localhost:8099/gsh/order/detail
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8099
  servlet:
    # 应用的访问路径
    context-path: /gsh
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    # tomcat临时文件目录 上传文件用
    basedir: /gsh/uploadPath/temp
# 日志配置
logging:
  level:
    com.gsh: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径iang
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid,solr
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 182.151.199.4
    # Redis服务器连接端口
    port: 11142
    # 密码（默认为空）
    password: root
    # 连接超时时长（毫秒）
    timeout: 10000
    lettuce:
      # 关闭超时时间 毫秒
      shutdown-timeout: 100
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 5000
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 10
  # Process 模块
  # 解决启动报错：class path resource [processes/] cannot be resolved to URL because it does not exist
  activiti:
    check-process-definitions: false
    # 检测身份信息表是否存在
    db-identity-used: false
    # 自动创建activity表
    #database-schema-update: true

# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.gsh
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 移动设备验证码开关
    mobileCaptchaEnabled: false
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
    #记住我的cookie失效时间，单位天
    maxAge: 3
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*,/subject/subject/addSubject/*,/subject/subject/saveSubject/*,/system/portalet/res/edit,/system/queryport/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*,/aiexam/*,/paper/*,/accessoriesInst/*,/subject/*,/AnswerInst/*,/userpaper/*

# minio 存储配置
minio:
  # 用户
  accessKey: admin
  # 口令
  secretKey: admin#123
  # url
  endpoint: http://182.151.199.4:11141
  # 存储桶
  gshBuketName: gsh
  # 默认的过期时间
  defaultDexpire: 300


